//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvertisingAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class advertising
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public advertising()
        {
            this.orders = new HashSet<order>();
        }
    
        public string name { get; set; }
        public string category { get; set; }
        public int price { get; set; }
        public string briefDescription { get; set; }
        public string fullDescription { get; set; }
        public string campaignName { get; set; }
    
        public virtual campaign campaign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
