//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvertisingAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int number { get; set; }
        public string about { get; set; }
        public System.DateTime createdDate { get; set; }
        public int customerId { get; set; }
        public int orderNumber { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual order order { get; set; }
    }
}
